#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 22 14:59:26 2018

@author: Thomas
"""
import numpy as np
import matplotlib.pyplot as plt

def gradesPlot(gradesFinal):
    
    grds = ('-3','00','02','4','7','10','12')
    x_pos = np.arange(len(grds))
    
    minus3 = gradesFinal == -3
    minus3 = np.extract(minus3,gradesFinal)
    A = np.size(minus3)
    
    zero = gradesFinal == 0
    zero = np.extract(zero,gradesFinal)
    B = np.size(zero)
    
    two = gradesFinal == 2
    two = np.extract(two,gradesFinal)
    C = np.size(two)
    
    four = gradesFinal == 4
    four = np.extract(four,gradesFinal)
    D = np.size(four)
    
    seven = gradesFinal == 7
    seven = np.extract(seven,gradesFinal)
    E = np.size(seven)
    
    ten = gradesFinal == 10
    ten = np.extract(ten,gradesFinal)
    F = np.size(ten)
    
    twelve = gradesFinal == 12
    twelve = np.extract(twelve,gradesFinal)
    G = np.size(twelve)
    
    occurences = [A,B,C,D,E,F,G]
    
    #Plots the data
    plt.bar(x_pos, occurences, align='center', alpha=1, color=['chocolate', 'indianred', 'dimgrey', 'springgreen', 'dodgerblue', 'fuchsia', 'gold'], width = 0.7, edgecolor = "k")
    plt.xticks(x_pos, grds,)
    plt.title('Grade Occurences')
    plt.xlabel('Grades', fontsize = 10)
    plt.ylabel('Occurences', fontsize = 10)
    plt.show()
    
    
    
    assignment = np.arange(np.size(grades,1))+1
    yaxis = np.arange(-3, 13)
    

    for i in range(grades[i,:]):
        minus3 = grades[i] == -3
        minus3 = np.extract(minus3,grades[i])
        minus3 = np.size(minus3)
        
        zero = grades[i] == 0
        zero = np.extract(zero,grades[i])
        zero = np.size(zero)
        
        two = grades[i] == 2
        two = np.extract(zero,grades[i])
        two = np.size(two)
        
        four = grades[i] == 4
        four = np.extract(zero,grades[i])
        four = np.size(four)
        
        seven = grades[i] == 7
        seven = np.extract(zero,grades[i])
        seven = np.size(seven)
        
        ten = grades[i] == 10
        ten = np.extract(zero,grades[i])
        ten = np.size(ten)
        
        twelve = grades[i] == 12
        twelve = np.extract(zero,grades[i])
        twelve = np.size(twelve)
        
    assignGrades = np.append(minus3, zero, two, four, seven, ten, twelve)
    
        
        

    


pik = np.array([1,2,3])
print(assignGrades)





grades = np.array([[7,7,7,7],[4,4,2,2],[-3,0,-3,-3]])

    
    
    
